name: flutter_agroflow
description: "Agricultural flow management system for suppliers and buyers"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI 
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  
  # Navigation
  go_router: ^14.3.0
  
  # Local Storage
  shared_preferences: ^2.3.3
  get_storage: ^2.1.1
  
  # Network
  dio: ^5.5.0+1
  connectivity_plus: ^6.1.0
  
  # Authentication & Backend
  supabase_flutter: ^2.7.0
  
  # Maps
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  
  # UI Components
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  
  # Forms
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.0.0
  
  # Charts
  fl_chart: ^0.69.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Image
  image_picker: ^1.1.2
  
  # File handling
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  
  # Animations
  lottie: ^3.1.3
  
  # Icons
  flutter_vector_icons: ^2.0.0
  
  # Toast & Dialogs
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Pretendard-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Pretendard-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Pretendard-Bold.ttf
  #         weight: 700
